# Generated by Django 5.2.16 on 2026-07-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=50, unique=True)),
                ('buy_average', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['script_name'],
            },
        ),
        migrations.CreateModel(
            name='CoveredCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sell_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_average', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_calls', to='portfolio.cashholding')),
            ],
            options={
                'ordering': ['-trade_date', 'holding__script_name'],
            },
        ),
    ]
