# Generated by Django 5.2.16 on 2026-07-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliocash_cashholding_close_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('INITIAL', 'Initial Capital'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('BUY', 'Buy Holding'), ('SELL', 'Sell Holding'), ('PREMIUM', 'Option Premium'), ('BUYBACK', 'Option Buyback'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='portfolio.cashholding')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioCash',
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_date'], name='portfolio_c_transac_c3db0e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_type'], name='portfolio_c_transac_ded1dd_idx'),
        ),
    ]
