# Generated by Django 5.2.16 on 2026-07-25 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cashtransaction_delete_portfoliocash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
