# Generated by Django 5.2.16 on 2026-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_cashtransaction_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveredcall',
            old_name='charges',
            new_name='closing_charges',
        ),
        migrations.AddField(
            model_name='coveredcall',
            name='opening_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
