# Generated by Django 5.2.16 on 2026-08-11 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_charges_coveredcall_closing_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.cashholding')),
            ],
            options={
                'ordering': ['-dividend_date', 'holding__script_name'],
                'indexes': [models.Index(fields=['dividend_date'], name='portfolio_d_dividen_87df4d_idx')],
            },
        ),
    ]
