# Generated by Django 5.2.16 on 2026-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Capital'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('BUY', 'Buy Holding'), ('SELL', 'Sell Holding'), ('PREMIUM', 'Option Premium'), ('BUYBACK', 'Option Buyback'), ('DIVIDEND', 'Dividend Income'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
    ]
